name: utilities
description: A new Flutter package project.
version: 0.0.1
homepage: SinaMN75.com
publish_to: 'none'

environment:
  sdk: '>=2.17.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  url_launcher: ^6.0.15
  get: ^4.6.3
  package_info_plus: ^1.4.3+1
  share_plus: ^4.0.10
  file_picker: ^5.2.4
  intl: ^0.17.0
  webviewx: ^0.2.1
  get_storage: ^2.0.3
  flutter_svg: ^1.1.1+1
  persian_tools: ^1.0.1
  group_button: ^5.2.0
  image_cropper: ^3.0.0
  cached_network_image: ^3.2.1
  video_player: ^2.4.6
  just_audio: ^0.9.27
  path_provider: ^2.0.11
  flutter_local_notifications: ^9.8.0+1
  flutter_easyloading: ^3.0.5
  pin_code_fields: ^7.4.0
  intl_phone_number_input: ^0.7.0+2
  flutter_image_compress: ^1.1.2
  dio: ^4.0.6
  dio_smart_retry: ^1.4.0
  local_auth: ^2.1.3
  local_auth_android: ^1.0.15
  local_auth_ios: ^1.0.10
  video_thumbnail: ^0.5.3
  video_box: ^0.17.0

#  Vide_player
  flick_video_player: ^0.5.0
  visibility_detector: ^0.3.3
  provider: ^6.0.5

  crypto: ^3.0.2

  photo_manager: ^2.2.1
  shimmer: ^2.0.0
  image_crop: ^0.4.1
  camera: ^0.10.0+1
  image: ^3.2.0
  image_picker: ^0.8.5+3
  fl_chart: ^0.61.0

  syncfusion_localizations: ^20.3.47
  syncfusion_flutter_datagrid_export: ^20.3.47-beta
  syncfusion_flutter_calendar: ^20.3.47
  syncfusion_flutter_datepicker: ^20.3.47
  syncfusion_flutter_charts: ^20.3.47
  syncfusion_flutter_gauges: ^20.3.47
  syncfusion_flutter_sliders: ^20.3.47
  syncfusion_flutter_pdf: ^20.3.47
  syncfusion_flutter_barcodes: ^20.3.47
  syncfusion_officechart: ^20.3.47-beta
  syncfusion_flutter_maps: ^20.3.47
  syncfusion_flutter_signaturepad: ^20.3.47
  syncfusion_flutter_pdfviewer: ^20.3.47-beta
  syncfusion_flutter_treemap: ^20.3.47-beta




flutter:
  uses-material-design: true
  assets:
    - lib/assets/data/